[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
event-bus.workspace = true
glfw.workspace = true
raw-window-handle.workspace = true
bgfx-rs.workspace = true
glam.workspace = true
uuid.workspace = true
image.workspace = true
log.workspace = true
